on:
  workflow_call: {}

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  actionlint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: reviewdog/action-actionlint@6fb7acc99f4a1008869fa8a0f09cfca740837d9d # v1.72.0
        with:
          fail_level: warning

  validate-renovate-config:
    uses: BlindfoldedSurgery/renovate-config/.github/workflows/validate.yml@main
    permissions:
      contents: read
