on:
  push:
    branches: [ main ]
  pull_request: { }

permissions:
  contents: read

jobs:
  required-meta:
    uses: ./.github/workflows/required.yml

  check-commits:
    uses: BlindfoldedSurgery/actions-releases/.github/workflows/commitizen-check.yml@v4
    with:
      build-tool: uv
      python-version: '3.14'

  commitizen-bump:
    uses: BlindfoldedSurgery/actions-releases/.github/workflows/commitizen-bump.yml@v4
    permissions:
      contents: write
      pull-requests: write
    with:
      build-tool: uv
      publish-major-tag: true
      python-version: '3.14'
    secrets:
      GH_TOKEN: ${{ secrets.GH_PR_TOKEN }}
