on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  required-meta:
    uses: ./.github/workflows/required.yml

  commitizen-check:
    uses: BlindfoldedSurgery/actions-releases/.github/workflows/commitizen-check.yml@v2
    with:
      build-tool: uv
      python-version: '3.13'

  commitizen-bump:
    uses: BlindfoldedSurgery/actions-releases/.github/workflows/commitizen-bump.yml@v2
    with:
      build-tool: uv
      publish-major-tag: true
      python-version: '3.13'
    secrets:
      GH_TOKEN: ${{ secrets.GH_PR_TOKEN }}
